name: pr_jobs

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.2.0'
      - name: Set env for common
        run: |
          echo "NEXT_PUBLIC_RESAS_API_KEY=${{ secrets.NEXT_PUBLIC_RESAS_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_RESAS_API_URL=${{ secrets.NEXT_PUBLIC_RESAS_API_URL }}" >> .env
          echo "NEXT_PUBLIC_SITE_BASE_URL=${{ secrets.NEXT_PUBLIC_SITE_BASE_URL }}" >> .env
      - name: Install Dependencies
        run: npm ci

      - name: Check Lint
        run: npm run lint
      - name: Check Build
        run: npm run build

      - name: Jest
        run: npm run test

      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: npm run build-storybook
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook"
