name: pr_jobs

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.2.0'
      - name: Install Dependencies
        run: npm ci
      - name: Check Lint
        run: npm run lint
      - name: Check Build
        run: npm run build
